name: 🚀 Release

on:
  push:
      branches:
          - main

jobs:
  lint:
    name: 🔎 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint

  test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test

  build:
    name: 📦 Build Next.js
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Build Next.js
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

  e2e:
    name: 🧪 End To End Tests
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: next-build
          path: .next
      - name: Run e2e test
        run: yarn e2e:test

  release:
    name: 🚀 Release
    needs:
      - e2e
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
